JoinMessagePre: ' &b&lWelcome back '
JoinMessagePost: '&b&l. '
QuitMessagePre: ' &cSadly, '
QuitMessagePost: '&c left. '
#  You cannot disable this plugin and must remove it to use the default minecraft messages (ew)
#  ------------------------------------------------------------------------------
#  COLORS
#  You can use & as the prefix for color coding your join/ leave messages
#  Reference:
#  https://www.colorschemer.com/minecraft-color-codes/
#  ------------------------------------------------------------------------------
#  JOIN MESSAGE
#  JoinMessagePre is the message BEFORE the player name
#  JoinMessagePost is after the player name
#  ------------------------------------------------------------------------------
#  QUIT MESSAGE
#  QuitMessagePre is the message BEFORE the player name
#  QuitMessagePost is after the player name
#  ------------------------------------------------------------------------------
#  A space after the message in MessagePre is recommended for best looking
#  UNICODE CHARACTERS DO NOT WORK CURRENTLY AND WILL BE FIXED IN THE NEXT UPDATE
#  ------------------------------------------------------------------------------
